void init(void);
void set_cursor(int);
void toggleE(void);
void lcd_writeChar(unsigned char );
void display_text_scroll(char *, int);
void display_text_noscroll(char *, int);
void display_text(char *, int, int);
void lcd_setLine(int);
void clearDisplay(void);
void wait(int);
